name: Database CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  database-deployment:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: project_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: Execute Initial Schema
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} < sql/01_initial_schema.sql

    - name: Execute Schema Update
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} < sql/02_schema_update.sql

    - name: Seed Sample Data
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} < sql/03_sample_data.sql

    - name: Run Concurrent Queries
      env:
        DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: |
        python scripts/multi_thread_queries.py

    - name: Validate Deployment
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "
          USE project_db;
          SELECT COUNT(*) FROM ClimateData;
          DESCRIBE ClimateData;
        " 