name: Database CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  database-deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: Cleanup Database
      run: |
        mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }} < sql/00_cleanup.sql

    - name: Execute Initial Schema
      run: |
        mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }} < sql/01_initial_schema.sql

    - name: Execute Schema Update
      run: |
        mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }} < sql/02_schema_update.sql

    - name: Seed Sample Data
      run: |
        mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }} < sql/03_sample_data.sql

    - name: Run Concurrent Queries
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python scripts/multi_thread_queries.py

    - name: Validate Deployment
      run: |
        mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "
          USE ${{ secrets.DB_NAME }};
          SELECT COUNT(*) FROM ClimateData;
          DESCRIBE ClimateData;
        " 